language: scala
jdk: oraclejdk8
scala: 2.12.4

stages:
  - name: test
  - name: release
    if: ((branch = master) AND (type != pull_request)) OR (tag IS present)

jobs:
  include:
    # default stage is test
    - env: TEST="compile"
      script: sbt compile
    # release only on merge commits or tags
    - stage: release
      script: if [[ "$(git rev-list --merges HEAD^..HEAD)" || "$TRAVIS_TAG" ]]; then sbt releaseEarly; else echo "skipping release"; fi

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
